language: java
jdk:
#  - openjdk6
#  - oraclejdk7
  - oraclejdk8
#  - openjdk7

before_install:
  - mvn install -DskipTests=true -e P dev

script:
  - mvn test -X

after_success:
  - mvn clean

branches:
  only:
    - videofile-jdk8

notifications:
  email:
    - bschlining@gmail.com
