/* DO NOT EDIT THIS FILE - it is machine generated */
#include <JavaVM/jni.h>
/* Header for class vars_avfoundation_AVFImageCaptureServiceImpl */

#ifndef _Included_vars_avfoundation_AVFImageCaptureServiceImpl
#define _Included_vars_avfoundation_AVFImageCaptureServiceImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     vars_avfoundation_AVFImageCaptureServiceImpl
 * Method:    videoDevicesAsStrings
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_vars_avfoundation_AVFImageCaptureServiceImpl_videoDevicesAsStrings
  (JNIEnv *, jobject);

/*
 * Class:     vars_avfoundation_AVFImageCaptureServiceImpl
 * Method:    startSessionWithNamedDevice
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_vars_avfoundation_AVFImageCaptureServiceImpl_startSessionWithNamedDevice
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vars_avfoundation_AVFImageCaptureServiceImpl
 * Method:    saveSnapshotToSpecifiedPath
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_vars_avfoundation_AVFImageCaptureServiceImpl_saveSnapshotToSpecifiedPath
  (JNIEnv *, jobject, jstring);

/*
 * Class:     vars_avfoundation_AVFImageCaptureServiceImpl
 * Method:    stopSession
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_vars_avfoundation_AVFImageCaptureServiceImpl_stopSession
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
