ALTER TABLE Association
	ADD LAST_UPDATED_TIME DATETIME NULL
GO

ALTER TABLE CameraData
    ADD LogDTG DATETIME NULL
GO

ALTER TABLE CameraData
    ADD LAST_UPDATED_TIME DATETIME NULL
GO

ALTER TABLE CameraPlatformDeployment
    ADD LAST_UPDATED_TIME DATETIME NULL
GO

ALTER TABLE Concept
    ADD LAST_UPDATED_TIME DATETIME NULL
GO

ALTER TABLE ConceptDelegate
    ADD LAST_UPDATED_TIME DATETIME NULL
GO

ALTER TABLE ConceptName
    ADD LAST_UPDATED_TIME DATETIME NULL
GO

ALTER TABLE History
    ADD LAST_UPDATED_TIME DATETIME NULL
GO

ALTER TABLE LinkRealization
    ADD LAST_UPDATED_TIME DATETIME NULL
GO

ALTER TABLE LinkTemplate
    ADD LAST_UPDATED_TIME DATETIME NULL
GO

ALTER TABLE Media
    ADD LAST_UPDATED_TIME DATETIME NULL
GO

ALTER TABLE Observation
    ADD LAST_UPDATED_TIME DATETIME NULL
GO

ALTER TABLE PhysicalData
    ADD LogDTG DATETIME NULL
GO

ALTER TABLE PhysicalData
    ADD LAST_UPDATED_TIME DATETIME NULL
GO

ALTER TABLE USAGE
    ADD LAST_UPDATED_TIME DATETIME NULL
GO

ALTER TABLE UserAccount
    ADD LAST_UPDATED_TIME DATETIME NULL
GO

ALTER TABLE UserAccount
    ADD Affiliation varchar(50) NULL
GO
ALTER TABLE UserAccount
    ADD FirstName varchar(50) NULL

GO
ALTER TABLE UserAccount
    ADD LastName varchar(50) NULL
GO

ALTER TABLE VideoArchive
    ADD LAST_UPDATED_TIME DATETIME NULL
GO

ALTER TABLE VideoArchiveSet
    ADD LAST_UPDATED_TIME DATETIME NULL
GO

ALTER TABLE VideoFrame
    ADD LAST_UPDATED_TIME DATETIME NULL
GO

UPDATE Concept
SET ParentConceptID_FK = NULL
WHERE ParentConceptID_FK = 0
GO

UPDATE Association
	SET LAST_UPDATED_TIME='2009-01-01 00:00:00'
	WHERE LAST_UPDATED_TIME IS NULL
GO

UPDATE CameraData
    SET LAST_UPDATED_TIME='2009-01-01 00:00:00'
    WHERE LAST_UPDATED_TIME IS NULL
GO

UPDATE CameraPlatformDeployment
    SET LAST_UPDATED_TIME='2009-01-01 00:00:00'
    WHERE LAST_UPDATED_TIME IS NULL
GO

UPDATE Concept
    SET LAST_UPDATED_TIME='2009-01-01 00:00:00'
    WHERE LAST_UPDATED_TIME IS NULL
GO

UPDATE ConceptDelegate
    SET LAST_UPDATED_TIME='2009-01-01 00:00:00'
    WHERE LAST_UPDATED_TIME IS NULL
GO

UPDATE ConceptName
    SET LAST_UPDATED_TIME='2009-01-01 00:00:00'
    WHERE LAST_UPDATED_TIME IS NULL
GO

UPDATE History
    SET LAST_UPDATED_TIME='2009-01-01 00:00:00'
    WHERE LAST_UPDATED_TIME IS NULL
GO

UPDATE LinkRealization
    SET LAST_UPDATED_TIME='2009-01-01 00:00:00'
    WHERE LAST_UPDATED_TIME IS NULL
GO

UPDATE LinkTemplate
    SET LAST_UPDATED_TIME='2009-01-01 00:00:00'
    WHERE LAST_UPDATED_TIME IS NULL
GO

UPDATE Media
    SET LAST_UPDATED_TIME='2009-01-01 00:00:00'
    WHERE LAST_UPDATED_TIME IS NULL
GO

UPDATE Observation
    SET LAST_UPDATED_TIME='2009-01-01 00:00:00'
    WHERE LAST_UPDATED_TIME IS NULL
GO


UPDATE PhysicalData
    SET LAST_UPDATED_TIME='2009-01-01 00:00:00'
    WHERE LAST_UPDATED_TIME IS NULL
GO

UPDATE USAGE
    SET LAST_UPDATED_TIME='2009-01-01 00:00:00'
    WHERE LAST_UPDATED_TIME IS NULL
GO

UPDATE UserAccount
    SET LAST_UPDATED_TIME='2009-01-01 00:00:00'
    WHERE LAST_UPDATED_TIME IS NULL
GO

UPDATE VideoArchive
    SET LAST_UPDATED_TIME='2009-01-01 00:00:00'
    WHERE LAST_UPDATED_TIME IS NULL
GO

UPDATE VideoArchiveSet
    SET LAST_UPDATED_TIME='2009-01-01 00:00:00'
    WHERE LAST_UPDATED_TIME IS NULL
GO

UPDATE VideoFrame
    SET LAST_UPDATED_TIME='2009-01-01 00:00:00'
    WHERE LAST_UPDATED_TIME IS NULL
GO

-- Allow case sensitive comparison. This is needed for the uc_ConceptName constraint to work correctly. 
-- May need to drop any indices on this column first
ALTER TABLE ConceptName 
    ALTER COLUMN ConceptName VARCHAR(50) COLLATE SQL_Latin1_General_CP1_CS_AS
GO

ALTER TABLE ConceptName
    ADD CONSTRAINT uc_ConceptName UNIQUE (ConceptName)
GO

-- Enforce the 1:1 relationship between Concept and ConceptDelegate tables
ALTER TABLE ConceptDelegate
    ADD CONSTRAINT uc_ConceptID_FK UNIQUE (ConceptID_FK)
GO

ALTER TABLE VideoArchive
    ADD CONSTRAINT uc_VideoArchiveName UNIQUE (VideoArchiveName)
GO

-- Enforce the 1:1 relationship between VideoFrame and CameraData tables
ALTER TABLE PhysicalData
    ADD CONSTRAINT uc_VideoFrameID_FK UNIQUE (VideoFrameID_FK)
GO

-- Enforce the 1:1 relationship between VideoFrame and CameraData tables
ALTER TABLE CameraData
    ADD CONSTRAINT uc_VideoFrameID_FK UNIQUE (VideoFrameID_FK)
GO

